Repository innovationacademy-kr/our42vent, pull requests merged in 2022-02, with the labels that each got.

#148 :bug: fix : 서버 공휴일 데이터 fetch 오류 #144
  db/cacheHolidays/cacheNextMonth.js
  db/cacheHolidays/holidaysUtils.js
Labels: enhancement

#141 :sparkles: feat : 서버에서 이벤트 폼 사용자 input 유효성 검증
  controllers/eventListController.js
  controllers/insertEventController.js
  lib/validateEventData.js
  public/javascripts/calendar/month/generateMonth.js
  public/javascripts/eventForm/addListenersForBorderColor.js
  public/javascripts/eventForm/checkTime.js
  public/javascripts/eventForm/clickNewEventButton.js
  public/javascripts/eventForm/utils/addCategoryEventListener.js
  public/javascripts/eventForm/utils/addTextEventListener.js
  public/javascripts/eventForm/utils/addTimeEventListener.js
  public/javascripts/eventList/addClickListenerForEdit.js
  public/javascripts/utils/eventForm/countByte.js
  public/javascripts/utils/eventForm/isValidEventForm.js
  views/components/eventForm.ejs
  views/layouts/desktopLayout.ejs
Labels: enhancement

#150 🔨 DB 쉘 스크립트 수정
  db/init/init_sql.sh
  db/init/set_token_event.sql
  db/init/start_event.sql
Labels: enhancement

#147 ✨ 이벤트 홍보글 생성 기능
  app.js
  controllers/eventController.js
  controllers/indexController.js
  controllers/insertEventController.js
  db/getIntraEvents/getFtAccessToken.js
  lib/validateEventData.js
  models/accessEventTable.js
  public/javascripts/calendar/month/addListenersAfterRender.js
  public/javascripts/eventDetail/clickEventDetails.js
  public/javascripts/eventDetail/clickExitButton.js
  public/javascripts/eventDetail/clickExitOrShareButton.js
  public/javascripts/eventForm/clickNewEventButton.js
  public/javascripts/eventInfo/eventInfo.js
  public/javascripts/eventList/setLayoutForEventList.js
  public/javascripts/eventPromotion/clickCopyPromotion.js
  public/javascripts/eventPromotion/clickExitPromotion.js
  public/javascripts/eventPromotion/generatePromotion.js
  public/stylesheets/components/popups/event_details.css
  public/stylesheets/components/popups/event_details_mobile.css
  public/stylesheets/components/popups/event_form_mobile.css
  public/stylesheets/components/popups/event_promotion.css
  public/stylesheets/presets/layout_desktop.css
  public/stylesheets/presets/mobile_spec.css
  public/stylesheets/style_desktop.css
  public/stylesheets/style_mobile.css
  routes/event.js
  views/components/eventDetails.ejs
  views/components/eventPromotion.ejs
  views/eventList.ejs
  views/index.ejs
  views/layouts/layout.ejs
Labels: enhancement

#152 ✨ 내가 생성한 이벤트 페이지에서 today기능 추가
  lib/validateEventData.js
  public/javascripts/calendar/month/clickToday.js
  public/javascripts/eventDetail/utils/setDuration.js
  public/javascripts/eventList/clickDelete.js
  public/javascripts/eventList/clickEdit.js
  public/javascripts/eventList/clickEventListToday.js
  public/javascripts/eventList/generateEventList.js
  public/javascripts/eventList/parseDate.js
  public/javascripts/eventList/renderEventListPage.js
  public/javascripts/eventList/setLayoutForEventList.js
  public/stylesheets/components/nav_toggle.css
  public/stylesheets/components/popups/event_details.css
  public/stylesheets/components/popups/event_details_mobile.css
  views/eventList.ejs
Labels: enhancement

#154 💄 모바일 UI 개선
  public/stylesheets/components/contents/event_list.css
  public/stylesheets/components/login.css
  public/stylesheets/components/nav.css
  public/stylesheets/presets/layout_desktop.css
  public/stylesheets/presets/mobile_spec.css
Labels: enhancement

#153 ✨ consoleLogger를 winston logger로 변경 및 로그 레벨에 맞게 에러 출력
  config/createRedisClient.js
  config/winston.js
  controllers/eventController.js
  controllers/initializePassport.js
  controllers/logoutController.js
  controllers/monthController.js
  controllers/myEventController.js
  lib/calendar/getHolidayCache.js
  lib/jwtUtils.js
  middlewares/verifyUser.js
  models/accessEventTable.js
  models/accessMyEventTable.js
  models/accessTokenRedis.js
  models/accessUserTable.js
  routes/login.js
Labels: enhancement

#155 :lipstick: 이벤트 띠지 & navbar ui 개선
  public/javascripts/calendar/month/addListenersAfterRender.js
  public/javascripts/calendar/month/clickToday.js
  public/javascripts/calendar/month/fillEventsUtils.js
  public/javascripts/calendar/month/generateMonth.js
  public/javascripts/calendar/month/mapLabelSlots.js
  public/javascripts/eventDetail/clickMyEventOrCancelButton.js
  public/javascripts/eventList/clickEventListToday.js
  public/javascripts/header/adjustNameSize.js
  public/javascripts/header/hoverTodayButton.js
  public/javascripts/header/userDropDown.js
  public/javascripts/nav/categoryFilterHandler.js
  public/javascripts/nav/initCheckboxes.js
  public/stylesheets/components/contents/month_calendar.css
  public/stylesheets/components/header.css
  public/stylesheets/components/nav.css
  public/stylesheets/components/nav_toggle.css
  public/stylesheets/components/popups/event_details.css
  public/stylesheets/components/popups/event_details_mobile.css
  public/stylesheets/components/popups/event_promotion.css
  public/stylesheets/presets/font.css
  public/stylesheets/presets/layout.css
  public/stylesheets/style_desktop.css
  public/stylesheets/style_mobile.css
  views/layouts/layout.ejs
Labels: enhancement

#156 :lipstick: touch 스크린에서 hover effect 없애기
  public/javascripts/calendar/month/addListenersAfterRender.js
  public/javascripts/calendar/month/changeMonth.js
  public/javascripts/calendar/month/drawMonth.js
  public/javascripts/calendar/month/generateMonth.js
  public/stylesheets/components/contents/event_list.css
  public/stylesheets/components/contents/month_calendar.css
  public/stylesheets/components/header.css
  public/stylesheets/components/login.css
  public/stylesheets/components/nav.css
  public/stylesheets/components/nav_toggle.css
  public/stylesheets/components/popups/event_details.css
  public/stylesheets/components/popups/event_details_mobile.css
  public/stylesheets/components/popups/event_form.css
  public/stylesheets/components/popups/event_form_mobile.css
  public/stylesheets/components/popups/event_promotion.css
  public/stylesheets/presets/mobile_spec.css
  public/stylesheets/presets/touch_responsive.css
  public/stylesheets/style_desktop.css
  public/stylesheets/style_mobile.css
Labels: enhancement

#163 :recycle: update 인트라 이벤트 로직 및 필터링 조건 변경
  controllers/eventController.js
  db/getIntraEvents/getEvents.js
  db/getIntraEvents/getFtAccessToken.js
  db/getIntraEvents/getUpdatedEvents.js
  db/init/create_table_event.sql
  lib/parseEventData.js
  public/javascripts/eventInfo/eventInfo.js
Labels: enhancement

#165 :lipstick: style : 이벤트 상세정보 팝업 x 위치 보정 & 띠지 user-select: none 적용
  public/javascripts/calendar/month/fillDateEvents.js
  public/stylesheets/components/popups/event_details.css
Labels: enhancement

#168 :sparkles: feat : 구글 애널리틱스 적용
  public/javascripts/config/setGoogleAnalytics.js
  views/layouts/layout.ejs
  views/login.ejs
Labels: enhancement

#164 ✨ Sentry 로거 추가 및 에러 핸들링
  .env.sample
  app.js
  config/helmet.js
  config/winston.js
  controllers/eventController.js
  controllers/insertEventController.js
  controllers/logoutController.js
  controllers/monthController.js
  controllers/myEventController.js
  lib/calendar/monthUtils.js
  lib/jwtUtils.js
  lib/validateEventData.js
  middlewares/errorHandler.js
  middlewares/verifyUser.js
  models/accessEventTable.js
  package-lock.json
  package.json
  public/assets/images/4xx.jpg
  public/assets/images/5xx.jpg
  public/assets/images/our42vent_logo_error.svg
  public/javascripts/calendar/month/generateMonth.js
  public/javascripts/config/sentry.js
  public/javascripts/eventDetail/clickEventDetails.js
  public/javascripts/eventDetail/clickMyEventOrCancelButton.js
  public/javascripts/eventForm/clickNewEventButton.js
  public/javascripts/eventList/clickDelete.js
  public/javascripts/eventList/clickEdit.js
  public/javascripts/eventList/generateEventList.js
  public/javascripts/utils/createAxiosInterceptor.js
  public/stylesheets/components/error.css
  routes/error.js
  routes/login.js
  views/error.ejs
  views/layouts/layout.ejs
Labels: enhancement

#172 :recycle: prefix를 사용하여 redis 영역 분리
  .env.sample
  models/accessTokenRedis.js
Labels: enhancement

#173 ✨ 이벤트 상세보기에서 url에 하이퍼링크 걸어주기#112
  public/javascripts/eventDetail/clickEventDetails.js
  public/javascripts/eventDetail/utils/replaceToHyperlink.js
  public/stylesheets/components/popups/event_details.css
  public/stylesheets/components/popups/event_details_mobile.css
Labels: enhancement

#177 ✨유저 이미지 로드 실패 시 기본 이미지 설정
  config/helmet.js
  controllers/logoutController.js
  public/assets/images/user_default.png
  public/javascripts/eventList/clickEdit.js
  public/javascripts/header/userDropDown.js
Labels: enhancement

#174 :sparkles: 이벤트 푸쉬 알림 기능 & 알림 UX 구현
  .env.sample
  app.js
  controllers/eventController.js
  controllers/insertEventController.js
  controllers/logoutController.js
  controllers/myEventController.js
  controllers/pushController.js
  db/init/create_table_my_event.sql
  db/init/create_table_push_subscription.sql
  db/init/init_sql.sh
  lib/push/pushUtils.js
  lib/push/triggerPush.js
  models/accessEventTable.js
  models/accessMyEventTable.js
  models/accessPushSubscriptionTable.js
  package-lock.json
  package.json
  public/assets/images/our42vent_badge.png
  public/javascripts/eventDetail/clickEventDetails.js
  public/javascripts/eventDetail/clickMyEventOrCancelButton.js
  public/javascripts/eventDetail/clickNotificationSelect.js
  public/javascripts/eventList/clickEdit.js
  public/javascripts/header/userDropDown.js
  public/javascripts/nav/categoryFilterHandler.js
  public/javascripts/nav/initCategoryCheckboxes.js
  public/javascripts/nav/tabSelectHandler.js
  public/javascripts/notification/initNotificationSetting.js
  public/javascripts/notification/subscribePushService.js
  public/serviceWorker.js
  public/stylesheets/components/contents/event_list.css
  public/stylesheets/components/header.css
  public/stylesheets/components/nav_toggle.css
  public/stylesheets/components/popups/event_details.css
  public/stylesheets/components/popups/event_details_mobile.css
  public/stylesheets/presets/color.css
  routes/calendar.js
  routes/event.js
  routes/push.js
  views/components/eventDetails.ejs
  views/index.ejs
  views/layouts/layout.ejs
  views/login.ejs
Labels: enhancement

#180 :memo: docs : README.md draft
  README.md
Labels: documentation

#184 :lipstick: sweetalert2 폰트 크기 수정
  public/stylesheets/presets/layout.css
  public/stylesheets/presets/mobile_spec.css
Labels: enhancement

#185 :recycle: api key 분리
  .env.sample
  config/createRedisClient.js
  db/getIntraEvents/getFtAccessToken.js
Labels: enhancement

#183 :bug: fix : 사용자가 알림 설정 꺼도 알림 정보 my_event 테이블에 유지되는 현상 #182
  README.md
  controllers/eventController.js
  controllers/pushController.js
  lib/push/pushUtils.js
  lib/push/triggerPush.js
  models/accessMyEventTable.js
  models/accessPushSubscriptionTable.js
  public/javascripts/notification/initNotificationSetting.js
Labels: bug

#187 ♻️ eventList 파일명 변경
  src/javascripts/entry/evenList.js
  src/javascripts/eventList_bundle.js
  src/javascripts/index_bundle.js
  src/javascripts/notification/subscribePushService.js
  webpack.config.js
Labels: enhancement

#189 :memo: docs : README.md 웹팩 배지 추가
  README.md
Labels: documentation

#190 :hammer: chore : GA 스크립트 위치 수정
  public/javascripts/setGoogleAnalytics.js
  views/layouts/layout.ejs
Labels: enhancement

#191 :sparkles: refactor : 이벤트 생성 후 홍보글 확인했을 때 바로 캘린더에 반영되도록 새로고침
  src/javascripts/eventForm/clickNewEventButton.js
  src/javascripts/eventPromotion/clickExitPromotion.js
Labels: enhancement

#193 :memo: docs : README.md 에 사용 가이드 링크 추가
  README.md
Labels: documentation

#194 :memo: docs : README.md 업데이트
  README.md
Labels: documentation

#198 💄 모달창에 경고 메시지 추가
  public/stylesheets/presets/layout.css
  public/stylesheets/presets/mobile_spec.css
  src/javascripts/eventDetail/clickMyEventOrCancelButton.js
Labels: enhancement

#197 💄 모달창에 경고 메시지 추가
  public/stylesheets/presets/layout.css
  public/stylesheets/presets/mobile_spec.css
  src/javascripts/eventDetail/clickMyEventOrCancelButton.js
Labels: enhancement

#200 🐛 연일 이벤트 띠지 배치 오류 fix
  package-lock.json
  src/javascripts/calendar/month/mapLabelSlots.js
  src/javascripts/header/hoverTodayButton.js
Labels: bug, enhancement

#201 🐛 연일 이벤트 띠지 배치 오류 fix (merge into develop)
  package-lock.json
  src/javascripts/calendar/month/mapLabelSlots.js
  src/javascripts/header/hoverTodayButton.js
Labels: bug, enhancement
